export {default as Home} from './Home'
export {default as About} from './About'
export {default as Error} from './Error'
export {default as Products} from './Products'
export {default as SingleProduct} from './SingleProduct'